name: Docker Image CI for GHCR

on: push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Build and push multi-architecture image
        run: |
          docker buildx create --use
          docker buildx build . \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/fourtyfy/docker_image-typo3web:latest \
            --push
